In [ ]:
import pandas as pd  #importing libraries
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dth = pd.read_csv("Hindi TV Serials.csv")
dth.head()

In [ ]:
dth = pd.read_csv("Hindi TV Serials.csv")
dth.head()

,Name,Ratings,genres,overview,Year,Cast
0,Kyunki Saas Bhi Kabhi Bahu Thi,1.6,"Comedy, Drama, Family",A mother-in-law's struggle to put up with her ...,2000–2008,"Smriti Malhotra-Irani ,Ronit Roy ,Amar Upadhya..."
1,Kahaani Ghar Ghar Kii,2.1,Drama,The show explored the worlds of its protagonis...,2000–2008,"Sakshi Tanwar ,Kiran Karmarkar ,Mita Vashisht ..."
2,Kesar,4.1,Family,"A story about a girl, Kesar, who fights for he...",2002–2007,"Nandini Singh ,Firoz Ali ,Hiten Tejwani ,Yash ..."
3,Kaahin Kissii Roz,6.0,Thriller,Shaina is beautiful and talented. Kunal is sua...,2001–2004,"Yash Tonk ,Sudha Chandran ,Mouli Ganguly ,Shwe..."
4,K. Street Pali Hill,7.4,Thriller,"A story about three friends relation, emotions...",2004–2006,"Ashwini Kalsekar ,Vikram Kapadia ,Jaswir Kaur ..."

In [ ]:
dth.describe() #getting statistical data

          Ratings
count  725.000000
mean     5.728828
std      2.861515
min      0.000000
25%      4.900000
50%      6.800000
75%      7.700000
max      9.700000

In [ ]:
dth.isnull().sum() #finding null values

Name         0
Ratings     19
genres       4
overview     0
Year        17
Cast        40
dtype: int64

In [ ]:
dth.dropna() #removing null values

,Name,Ratings,genres,overview,Year,Cast
0,Kyunki Saas Bhi Kabhi Bahu Thi,1.6,"Comedy, Drama, Family",A mother-in-law's struggle to put up with her ...,2000–2008,"Smriti Malhotra-Irani ,Ronit Roy ,Amar Upadhya..."
1,Kahaani Ghar Ghar Kii,2.1,Drama,The show explored the worlds of its protagonis...,2000–2008,"Sakshi Tanwar ,Kiran Karmarkar ,Mita Vashisht ..."
2,Kesar,4.1,Family,"A story about a girl, Kesar, who fights for he...",2002–2007,"Nandini Singh ,Firoz Ali ,Hiten Tejwani ,Yash ..."
3,Kaahin Kissii Roz,6.0,Thriller,Shaina is beautiful and talented. Kunal is sua...,2001–2004,"Yash Tonk ,Sudha Chandran ,Mouli Ganguly ,Shwe..."
4,K. Street Pali Hill,7.4,Thriller,"A story about three friends relation, emotions...",2004–2006,"Ashwini Kalsekar ,Vikram Kapadia ,Jaswir Kaur ..."
...,...,...,...,...,...,...
739,Kaamnaa,7.2,Drama,'Kamna' is bringing the story of the conflict ...,2021–,"Abhishek Rawat ,Chandni Sharma ,Suraj Singhan ..."
740,Dhadkan Zindaggi Kii,8.9,Drama,"In a world where rules are set by men, Dr Deep...",2021–,"Additi Gupta ,Rohit Purohit ,Vidyut Xavier ,Al..."
741,Mose Chhal Kiye Jaaye,6.9,Drama,Serial showcases a story of girl named Saumya(...,2022–,"Vidhi Pandya ,Vijayendra Kumeria ,Alka Badola ..."
742,Jagannath Aur Purvi Ki Dosti Anokhi,9.2,Drama,"Jagannath Mishra, an elderly gentleman, saves ...",2022–,"Rajendra Gupta ,Sushmita Mukherjee ,Ismeet Koh..."
743,Shark Tank India,8.9,Reality-TV,Aspiring entrepreneurs from India pitch their ...,2021–,"Anupam Mittal ,Namita Thapar ,Ashneer Grover ,..."

In [ ]:
dth = dth.reset_index(drop=True) #resetting index numbers after removing null value
dth

,Name,Ratings,genres,overview,Year,Cast
0,Kyunki Saas Bhi Kabhi Bahu Thi,1.6,"Comedy, Drama, Family",A mother-in-law's struggle to put up with her ...,2000–2008,"Smriti Malhotra-Irani ,Ronit Roy ,Amar Upadhya..."
1,Kahaani Ghar Ghar Kii,2.1,Drama,The show explored the worlds of its protagonis...,2000–2008,"Sakshi Tanwar ,Kiran Karmarkar ,Mita Vashisht ..."
2,Kesar,4.1,Family,"A story about a girl, Kesar, who fights for he...",2002–2007,"Nandini Singh ,Firoz Ali ,Hiten Tejwani ,Yash ..."
3,Kaahin Kissii Roz,6.0,Thriller,Shaina is beautiful and talented. Kunal is sua...,2001–2004,"Yash Tonk ,Sudha Chandran ,Mouli Ganguly ,Shwe..."
4,K. Street Pali Hill,7.4,Thriller,"A story about three friends relation, emotions...",2004–2006,"Ashwini Kalsekar ,Vikram Kapadia ,Jaswir Kaur ..."
...,...,...,...,...,...,...
739,Kaamnaa,7.2,Drama,'Kamna' is bringing the story of the conflict ...,2021–,"Abhishek Rawat ,Chandni Sharma ,Suraj Singhan ..."
740,Dhadkan Zindaggi Kii,8.9,Drama,"In a world where rules are set by men, Dr Deep...",2021–,"Additi Gupta ,Rohit Purohit ,Vidyut Xavier ,Al..."
741,Mose Chhal Kiye Jaaye,6.9,Drama,Serial showcases a story of girl named Saumya(...,2022–,"Vidhi Pandya ,Vijayendra Kumeria ,Alka Badola ..."
742,Jagannath Aur Purvi Ki Dosti Anokhi,9.2,Drama,"Jagannath Mishra, an elderly gentleman, saves ...",2022–,"Rajendra Gupta ,Sushmita Mukherjee ,Ismeet Koh..."
743,Shark Tank India,8.9,Reality-TV,Aspiring entrepreneurs from India pitch their ...,2021–,"Anupam Mittal ,Namita Thapar ,Ashneer Grover ,..."

In [ ]:
print(dth.sort_values(["Ratings"], ascending=False)) #to display data in the descending order of rating

In [ ]:
def clean_genre_list(list_):       #defining library to slice plot description
    if type(list_) is str:
        list_ = "[" + list_ + "]"
        list_ = list_.replace(',', '","')
        list_ = list_.replace('[', '["')
        list_ = list_.replace(']', '"]')
        list_ = list_.replace(' "', '"')
        list_ = list_.replace(" ","")
        return list_
    else:
        return "[]"

In [ ]:
dth["genres"] = dth["genres"].apply(clean_genre_list)
dth["genres"] = dth["genres"].apply(eval)

In [ ]:
def to_1D(series):
    return pd.Series([x for _list in series for x in _list])

In [ ]:
df_genre_imdb = dfmain.groupby(to_1D(dfmain["genres"])).mean()
print(df_genre_imdb.sort_values(["Ratings"],ascending=False))

NameError: ignored

In [ ]:
df_genre_count = to_1D(dfmain["genres"]).value_counts()
print(df_genre_count)

df_genre_count.plot(kind = 'bar')
plt.show()

In [ ]:
def findstart(list_):
    if type(list_) is str:
        list_ = list_[:4]
        return list_
    else:
        return ""

def duration(list_):
    if type(list_) is str:
        if len(list_) == 9 and list_[0]!="I":
            l1 = int(list_[:4])
            l2 = int(list_[5:])
            return l2-l1
        else:
            return 0
    else:
        return 0

dfmain["First Year"] = dfmain["Year"].apply(findstart)
dfmain["Years Run"] = dfmain["Year"].apply(duration)

In [ ]:
df_year_count = dfmain["First Year"].value_counts().sort_index()
df_year_count = df_year_count.iloc[:-4] #removing the weird I values

df_year_count.plot(kind = 'bar')
plt.show()

In [ ]:
print(dfmain.sort_values(["Years Run"], ascending=False))

In [ ]:
def clean_ovw_list(list_):

    if type(list_) is str:
        list_ = "[" + list_ + "]"

        #removing all the special characters
        list_ = list_.replace(',', '')
        list_ = list_.replace('.', '')
        list_ = list_.replace('"', '')
        list_ = list_.replace('(', '')
        list_ = list_.replace(')', '')
        list_ = list_.replace('-', '')
        list_ = list_.replace('»', '')

        list_ = list_.replace(' ', '","')
        list_ = list_.replace('[', '["')
        list_ = list_.replace(']', '"]')
        list_ = list_.replace(' "', '"')

        #converting to lower case
        list_ = list_.lower()
        return list_
    else:
        return "[]"

In [ ]:
dfmain["overview"] = dfmain["overview"].apply(clean_ovw_list)
dfmain["overview"] = dfmain["overview"].apply(eval)

In [ ]:
df_ovwcount = dfmain.groupby(['First Year',to_1D(dfmain["overview"])]).count().reset_index()

In [ ]:
df_ovw_count_simple = to_1D(dfmain["overview"]).value_counts()
print(df_ovw_count_simple.head(50))